from pydantic import BaseModel
from datetime import datetime
from typing import Optional


class TaskCreate(
    BaseModel
):  # What information should the user provide when creating a task?
    # Input Model
    title: str
    description: Optional[str] = None  # If user doent send it


class Task(BaseModel):  # this value Will be Generated By the server
    # output Model
    id: int
    title: str
    description: Optional[str] = None
    completed: bool
    created_at: datetime


class Task_Updated(BaseModel):
    title: str
    description: Optional[str] = None
    completed: bool
